# Generated by Django 5.0.2 on 2026-06-27 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título del proyecto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='Ubicación aproximada')),
                ('work_date', models.DateField(blank=True, null=True, verbose_name='Fecha del trabajo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/', verbose_name='Foto de portada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='workers.service', verbose_name='Tipo de servicio')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workers.worker', verbose_name='Trabajador / maestro')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/photos/', verbose_name='Imagen')),
                ('kind', models.CharField(choices=[('before', 'Antes'), ('after', 'Después'), ('general', 'General')], default='general', max_length=10, verbose_name='Tipo de foto')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Descripción corta')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Foto de proyecto',
                'verbose_name_plural': 'Fotos de proyectos',
            },
        ),
    ]
