# Generated by Django 5.0.2 on 2026-06-27 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del ícono usado en el frontend, ej: "plumbing".', max_length=50, verbose_name='Ícono')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workers.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_type', models.CharField(choices=[('obrero', 'Obrero'), ('maestro', 'Maestro de obra')], default='obrero', max_length=20, verbose_name='Tipo')),
                ('headline', models.CharField(blank=True, help_text='Ej: "Gasfitero certificado", "Maestro albañil".', max_length=120, verbose_name='Oficio / especialidad')),
                ('bio', models.TextField(blank=True, verbose_name='Descripción profesional')),
                ('work_zone', models.CharField(blank=True, max_length=150, verbose_name='Zona de trabajo')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Años de experiencia')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='workers/profiles/', verbose_name='Foto de perfil')),
                ('show_phone', models.BooleanField(default=False, verbose_name='Mostrar teléfono/WhatsApp')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado por Cuadrilla Maestra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Perfil activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='workers.category', verbose_name='Oficio principal')),
                ('services', models.ManyToManyField(blank=True, related_name='workers', to='workers.service', verbose_name='Servicios que ofrece')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Obrero / Maestro',
                'verbose_name_plural': 'Obreros y maestros',
                'ordering': ['-is_verified', '-created_at'],
            },
        ),
    ]
