# Generated by Django 5.0.2 on 2026-06-27 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('contact', 'Contacto'), ('quote', 'Cotización')], default='quote', max_length=10, verbose_name='Tipo')),
                ('client_name', models.CharField(max_length=120, verbose_name='Nombre del cliente')),
                ('client_phone', models.CharField(max_length=20, verbose_name='Teléfono / WhatsApp')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('zone', models.CharField(blank=True, max_length=150, verbose_name='Zona / distrito')),
                ('message', models.TextField(verbose_name='Mensaje / descripción del trabajo')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('in_progress', 'En proceso'), ('closed', 'Cerrada')], default='new', max_length=15, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='workers.service', verbose_name='Servicio de interés')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='workers.worker', verbose_name='Trabajador / maestro')),
            ],
            options={
                'verbose_name': 'Solicitud de contacto / cotización',
                'verbose_name_plural': 'Solicitudes de contacto / cotización',
                'ordering': ['-created_at'],
            },
        ),
    ]
