# Generated by Django 5.0.2 on 2026-06-27 07:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120, verbose_name='Nombre del cliente')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('service_hired', models.CharField(blank=True, max_length=150, verbose_name='Servicio contratado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_written', to=settings.AUTH_USER_MODEL, verbose_name='Usuario autor')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='workers.worker', verbose_name='Trabajador / maestro')),
            ],
            options={
                'verbose_name': 'Reseña de cliente',
                'verbose_name_plural': 'Reseñas de clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=120, verbose_name='Nombre del supervisor')),
                ('punctuality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntualidad')),
                ('work_quality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calidad del trabajo')),
                ('cleanliness', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Limpieza')),
                ('safety', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Seguridad')),
                ('customer_treatment', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Trato al cliente')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario del supervisor')),
                ('evaluated_at', models.DateField(auto_now_add=True, verbose_name='Fecha de evaluación')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_made', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_evaluation', to='workers.worker', verbose_name='Trabajador / maestro')),
            ],
            options={
                'verbose_name': 'Evaluación de supervisor',
                'verbose_name_plural': 'Evaluaciones de supervisores',
            },
        ),
    ]
